[build]
target = "./thumbv6m-none-espidf-eabi.json"

[target.thumbv6m-none-espidf-eabi]
runner = "elf2uf2-rs -d -s"
linker = "ldproxy"
rustflags = ["-C", "default-linker-libraries=yes"]

[unstable]
build-std = ["std", "panic_abort"]